# Generated by Django 3.2.19 on 2023-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_auto_20230517_1346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="lname",
        ),
    ]
