# Generated by Django 3.2.19 on 2023-05-17 13:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="recipes/",
            ),
        ),
    ]
