# Generated by Django 3.2.19 on 2023-05-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_alt',
        ),
    ]
